kind: MLApp
metadata:
  name: bigdl
spec:
  package_manager: "pip{{.python_version.value}}"
  default_mount_path: "/notebooks"
  packages:
    - names:
      {{- range $i, $value := .packages }}
      - "{{ $value }}"
      {{- end }}
      manager: "pip{{.python_version.value}}"
  tasks:
  {{- if and ( not .spark_master ) (eq .spark_type.value "cluster") }}
  - name: spark-workers
    resources:
    - name: workers
      replicas: 1
      restartPolicy: Never
      maxRestartCount: 0
      {{- if eq .python_version.value "3" }}
      images:
        cpu: "kuberlab/pyspark:cpu-36-full"
      {{- end }}
      {{- if eq .python_version.value "2" }}
      images:
        cpu: "kuberlab/pyspark:cpu-27-full"
      {{- end }}
      command: "spark-class org.apache.spark.deploy.worker.Worker $SPARK_MASTER"
      workdir: "$SRC_DIR"
      env:
      - name: SPARK_MASTER
        value: {{"spark://{{.PROJECT_NAME}}-spark:7077"}}
      resources:
        accelerators:
          gpu: 0
        requests:
          cpu: 100m
          memory: 64Mi
        limits:
          cpu: 1000m
          memory: 8Gi
      default_volume_mapping: true
  {{- end }}
  - name: spark-job
    resources:
    - name: job
      replicas: 1
      restartPolicy: Never
      maxRestartCount: 0
      {{- if eq .python_version.value "3" }}
      images:
        cpu: "kuberlab/pyspark:cpu-36-full"
      {{- end }}
      {{- if eq .python_version.value "2" }}
      images:
        cpu: "kuberlab/pyspark:cpu-27-full"
      {{- end }}
      command: "python test.py"
      workdir: "$SRC_DIR/src"
      resources:
        accelerators:
          gpu: 0
        requests:
          cpu: 100m
          memory: 64Mi
        limits:
          cpu: 1000m
          memory: 4Gi
      env:
      {{- if .spark_master }}
      - name: SPARK_MASTER
        value: {{ .spark_master }}
      {{- else if eq .spark_type.value "cluster" }}
      - name: SPARK_MASTER
        value: {{"spark://{{.PROJECT_NAME}}-spark:7077"}}
      {{- else }}
      - name: SPARK_MASTER
        value: "local[*]"
      {{- end }}
      port: 2222
      default_volume_mapping: true
    {{- if and ( not .spark_master ) (eq .spark_type.value "cluster") }}
    - name: worker
      replicas: 1
      restartPolicy: Never
      maxRestartCount: 0
      is_permanent: true
      {{- if eq .python_version.value "3" }}
      images:
        cpu: "kuberlab/pyspark:cpu-36-full"
      {{- end }}
      {{- if eq .python_version.value "2" }}
      images:
        cpu: "kuberlab/pyspark:cpu-27-full"
      {{- end }}
      command: "spark-class org.apache.spark.deploy.worker.Worker $SPARK_MASTER"
      workdir: "$SRC_DIR"
      port: 2222
      env:
      - name: SPARK_MASTER
        value: {{"spark://{{.PROJECT_NAME}}-spark:7077"}}
      volumes:
      - name: lib
      - name: training
    {{- end }}
  uix:
  - name: jupyter
    displayName: Jupyter
    {{- if eq .python_version.value "3" }}
    images:
      cpu: "kuberlab/pyspark:cpu-36-full"
    {{- end }}
    {{- if eq .python_version.value "2" }}
    images:
      cpu: "kuberlab/pyspark:cpu-27-full"
    {{- end }}
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 1000m
        memory: 4Gi
    env:
    {{- if .spark_master }}
    - name: SPARK_MASTER
      value: {{ .spark_master }}
    {{- else if eq .spark_type.value "cluster" }}
    - name: SPARK_MASTER
      value: {{"spark://{{.PROJECT_NAME}}-spark:7077"}}
    {{- else }}
    - name: SPARK_MASTER
      value: "local[*]"
    {{- end }}
    ports:
    - port: 8888
      targetPort: 8888
      protocol: TCP
      name: http
    default_volume_mapping: true
  {{- if eq .spark_type.value "cluster" }}
  - name: spark
    displayName: Spark
    command: "echo $(hostname -i) $PROJECT_NAME-spark >> /etc/hosts  && spark-class -Dspark.ui.proxyBase=/../../../../../../../$URL_PREFIX org.apache.spark.deploy.master.Master --port 7077 --webui-port 8080 --host $PROJECT_NAME-spark"
    {{- if eq .python_version.value "3" }}
    images:
      cpu: "kuberlab/pyspark:cpu-36-full"
    {{- end }}
    {{- if eq .python_version.value "2" }}
    images:
      cpu: "kuberlab/pyspark:cpu-27-full"
    {{- end }}
    ports:
    - port: 7077
      targetPort: 7077
      protocol: TCP
      name: service
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: web
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 1000m
        memory: 2Gi
    volumes:
    - name: lib
    - name: training
    - name: data
  {{- end }}
  volumes:
  - isLibDir: false
    name: training
    clusterStorage: {{ .storage.value }}
  - gitRepo:
      repository: https://github.com/kuberlab-catalog/bigdl-template
    isLibDir: false
    name: src
    subPath: bigdl-template
  - isLibDir: true
    name: lib
    clusterStorage: {{ .storage.value }}
  - isLibDir: false
    name: data
    clusterStorage: {{ .storage.value }}
  - isLibDir: false
    mountPath: /notebooks
    name: code
    subPath: code
    clusterStorage: {{ .storage.value }}
