storage:
 value: default
 wizard:
   name: "Storage Configuration"
   kind: cluster_storage

python_version:
  value: "2"
  wizard:
    name: "Python version"
    kind: select
    options:
    - "2"
    - "3"

