storage:
 value: default
 wizard:
   name: "Storage Configuration"
   kind: cluster_storage

python_version:
  value: "2"
  wizard:
    name: "Python version"
    kind: select
    options:
    - "2"
    - "3"

src:
  value: https://github.com/kuberlab/spark-bigdl-examples
  wizard:
    name: "Source Code"
    kind: git

spark_type:
  value: "cluster"
  wizard:
    name: "Local or Cluster spark mode. Or use external spark cluster."
    kind: select
    dynamic: true
    options:
    - "cluster"
    - "local"

dataset:
 value: ''
 version: ''
 workspace: ''
 wizard:
   name: "Dataset configuration"
   kind: dataset
