storage:
 value: default
 wizard:
   name: "Storage Configuration"
   kind: cluster_storage

python_version:
  value: "2"
  wizard:
    name: "Python version"
    kind: select
    options:
    - "2"
    - "3"

spark_master: ""
spark_type:
  value: "cluster"
  wizard:
    name: "Local or Cluster spark mode"
    kind: select
    options:
    - "cluster"
    - "local"

